inc= /home/seth-linux-pc/Documents/Big_Cpp_Source_Code/cccfiles
lib=/home/seth-linux-pc/Documents/Big_Cpp_Lib

program: $(inc) $(lib)
	g++ -I $(inc) programmer.cpp main.cpp -L $(lib) -lccc -lX11 -o program

